// Every Dota 2 hero: [id, display name, CDN slug, primary attribute].
// Generated from the dotaconstants package (OpenDota). When Valve adds a hero,
// append a row here — the slug is the npc_dota_hero_<slug> internal name.
// Classic script (not a module) so the page still opens from file:// too.
window.SS_HEROES = [
  [102,"Abaddon","abaddon","all"],
  [73,"Alchemist","alchemist","str"],
  [68,"Ancient Apparition","ancient_apparition","int"],
  [1,"Anti-Mage","antimage","agi"],
  [113,"Arc Warden","arc_warden","all"],
  [2,"Axe","axe","str"],
  [3,"Bane","bane","all"],
  [65,"Batrider","batrider","all"],
  [38,"Beastmaster","beastmaster","all"],
  [4,"Bloodseeker","bloodseeker","agi"],
  [62,"Bounty Hunter","bounty_hunter","agi"],
  [78,"Brewmaster","brewmaster","all"],
  [99,"Bristleback","bristleback","str"],
  [61,"Broodmother","broodmother","agi"],
  [96,"Centaur Warrunner","centaur","str"],
  [81,"Chaos Knight","chaos_knight","str"],
  [66,"Chen","chen","int"],
  [56,"Clinkz","clinkz","agi"],
  [51,"Clockwerk","rattletrap","str"],
  [5,"Crystal Maiden","crystal_maiden","int"],
  [55,"Dark Seer","dark_seer","int"],
  [119,"Dark Willow","dark_willow","int"],
  [135,"Dawnbreaker","dawnbreaker","str"],
  [50,"Dazzle","dazzle","all"],
  [43,"Death Prophet","death_prophet","all"],
  [87,"Disruptor","disruptor","int"],
  [69,"Doom","doom_bringer","str"],
  [49,"Dragon Knight","dragon_knight","str"],
  [6,"Drow Ranger","drow_ranger","agi"],
  [107,"Earth Spirit","earth_spirit","str"],
  [7,"Earthshaker","earthshaker","str"],
  [103,"Elder Titan","elder_titan","str"],
  [106,"Ember Spirit","ember_spirit","agi"],
  [58,"Enchantress","enchantress","int"],
  [33,"Enigma","enigma","all"],
  [41,"Faceless Void","faceless_void","agi"],
  [121,"Grimstroke","grimstroke","int"],
  [72,"Gyrocopter","gyrocopter","agi"],
  [123,"Hoodwink","hoodwink","agi"],
  [59,"Huskar","huskar","str"],
  [74,"Invoker","invoker","int"],
  [91,"Io","wisp","all"],
  [64,"Jakiro","jakiro","int"],
  [8,"Juggernaut","juggernaut","agi"],
  [90,"Keeper of the Light","keeper_of_the_light","int"],
  [145,"Kez","kez","agi"],
  [23,"Kunkka","kunkka","str"],
  [155,"Largo","largo","str"],
  [104,"Legion Commander","legion_commander","str"],
  [52,"Leshrac","leshrac","int"],
  [31,"Lich","lich","int"],
  [54,"Lifestealer","life_stealer","str"],
  [25,"Lina","lina","int"],
  [26,"Lion","lion","int"],
  [80,"Lone Druid","lone_druid","agi"],
  [48,"Luna","luna","agi"],
  [77,"Lycan","lycan","str"],
  [97,"Magnus","magnataur","all"],
  [136,"Marci","marci","all"],
  [129,"Mars","mars","str"],
  [94,"Medusa","medusa","agi"],
  [82,"Meepo","meepo","agi"],
  [9,"Mirana","mirana","agi"],
  [114,"Monkey King","monkey_king","agi"],
  [10,"Morphling","morphling","agi"],
  [138,"Muerta","muerta","int"],
  [89,"Naga Siren","naga_siren","agi"],
  [53,"Nature's Prophet","furion","all"],
  [36,"Necrophos","necrolyte","int"],
  [60,"Night Stalker","night_stalker","str"],
  [88,"Nyx Assassin","nyx_assassin","all"],
  [84,"Ogre Magi","ogre_magi","str"],
  [57,"Omniknight","omniknight","str"],
  [111,"Oracle","oracle","int"],
  [76,"Outworld Devourer","obsidian_destroyer","int"],
  [120,"Pangolier","pangolier","all"],
  [44,"Phantom Assassin","phantom_assassin","agi"],
  [12,"Phantom Lancer","phantom_lancer","agi"],
  [110,"Phoenix","phoenix","str"],
  [137,"Primal Beast","primal_beast","str"],
  [13,"Puck","puck","int"],
  [14,"Pudge","pudge","str"],
  [45,"Pugna","pugna","int"],
  [39,"Queen of Pain","queenofpain","int"],
  [15,"Razor","razor","agi"],
  [32,"Riki","riki","agi"],
  [131,"Ring Master","ringmaster","int"],
  [86,"Rubick","rubick","int"],
  [16,"Sand King","sand_king","all"],
  [79,"Shadow Demon","shadow_demon","int"],
  [11,"Shadow Fiend","nevermore","agi"],
  [27,"Shadow Shaman","shadow_shaman","int"],
  [75,"Silencer","silencer","int"],
  [101,"Skywrath Mage","skywrath_mage","int"],
  [28,"Slardar","slardar","str"],
  [93,"Slark","slark","agi"],
  [128,"Snapfire","snapfire","all"],
  [35,"Sniper","sniper","agi"],
  [67,"Spectre","spectre","agi"],
  [71,"Spirit Breaker","spirit_breaker","str"],
  [17,"Storm Spirit","storm_spirit","int"],
  [18,"Sven","sven","str"],
  [105,"Techies","techies","all"],
  [46,"Templar Assassin","templar_assassin","agi"],
  [109,"Terrorblade","terrorblade","agi"],
  [29,"Tidehunter","tidehunter","str"],
  [98,"Timbersaw","shredder","str"],
  [34,"Tinker","tinker","int"],
  [19,"Tiny","tiny","str"],
  [83,"Treant Protector","treant","str"],
  [95,"Troll Warlord","troll_warlord","agi"],
  [100,"Tusk","tusk","str"],
  [108,"Underlord","abyssal_underlord","str"],
  [85,"Undying","undying","str"],
  [70,"Ursa","ursa","agi"],
  [20,"Vengeful Spirit","vengefulspirit","agi"],
  [40,"Venomancer","venomancer","all"],
  [47,"Viper","viper","agi"],
  [92,"Visage","visage","all"],
  [126,"Void Spirit","void_spirit","all"],
  [37,"Warlock","warlock","int"],
  [63,"Weaver","weaver","agi"],
  [21,"Windranger","windrunner","all"],
  [112,"Winter Wyvern","winter_wyvern","int"],
  [30,"Witch Doctor","witch_doctor","int"],
  [42,"Wraith King","skeleton_king","str"],
  [22,"Zeus","zuus","int"]
];
