// Every Dota 2 item: [id, internal name, display name, neutral item (1/0)].
// Generated from the dotaconstants package (OpenDota). When Valve adds an item,
// append a row here — the internal name is also its picture's file name on
// Steam's CDN (images/dota_react/items/<name>.png).
// Classic script (not a module) so the page still opens from file:// too.
window.SS_ITEMS = [
  [1, "blink", "Blink Dagger", 0],
  [2, "blades_of_attack", "Blades of Attack", 0],
  [3, "broadsword", "Broadsword", 0],
  [4, "chainmail", "Chainmail", 0],
  [5, "claymore", "Claymore", 0],
  [6, "helm_of_iron_will", "Helm of Iron Will", 0],
  [7, "javelin", "Javelin", 0],
  [8, "mithril_hammer", "Mithril Hammer", 0],
  [9, "platemail", "Platemail", 0],
  [10, "quarterstaff", "Quarterstaff", 0],
  [11, "quelling_blade", "Quelling Blade", 0],
  [12, "ring_of_protection", "Ring of Protection", 0],
  [13, "gauntlets", "Gauntlets of Strength", 0],
  [14, "slippers", "Slippers of Agility", 0],
  [15, "mantle", "Mantle of Intelligence", 0],
  [16, "branches", "Iron Branch", 0],
  [17, "belt_of_strength", "Belt of Strength", 0],
  [18, "boots_of_elves", "Band of Elvenskin", 0],
  [19, "robe", "Robe of the Magi", 0],
  [20, "circlet", "Circlet", 0],
  [21, "ogre_axe", "Ogre Axe", 0],
  [22, "blade_of_alacrity", "Blade of Alacrity", 0],
  [23, "staff_of_wizardry", "Staff of Wizardry", 0],
  [24, "ultimate_orb", "Ultimate Orb", 0],
  [25, "gloves", "Gloves of Haste", 0],
  [26, "lifesteal", "Morbid Mask", 0],
  [27, "ring_of_regen", "Ring of Regen", 0],
  [28, "sobi_mask", "Sage's Mask", 0],
  [29, "boots", "Boots of Speed", 0],
  [30, "gem", "Gem of True Sight", 0],
  [31, "cloak", "Cloak", 0],
  [32, "talisman_of_evasion", "Talisman of Evasion", 0],
  [33, "cheese", "Cheese", 0],
  [34, "magic_stick", "Magic Stick", 0],
  [36, "magic_wand", "Magic Wand", 0],
  [37, "ghost", "Ghost Scepter", 0],
  [38, "clarity", "Clarity", 0],
  [39, "flask", "Healing Salve", 0],
  [40, "dust", "Dust of Appearance", 0],
  [41, "bottle", "Bottle", 0],
  [42, "ward_observer", "Observer Ward", 0],
  [43, "ward_sentry", "Sentry Ward", 0],
  [44, "tango", "Tango", 0],
  [45, "courier", "Animal Courier", 0],
  [46, "tpscroll", "Town Portal Scroll", 0],
  [48, "travel_boots", "Boots of Travel", 0],
  [50, "phase_boots", "Phase Boots", 0],
  [51, "demon_edge", "Demon Edge", 0],
  [52, "eagle", "Eaglesong", 0],
  [53, "reaver", "Reaver", 0],
  [54, "relic", "Sacred Relic", 0],
  [55, "hyperstone", "Hyperstone", 0],
  [56, "ring_of_health", "Ring of Health", 0],
  [57, "void_stone", "Void Stone", 0],
  [58, "mystic_staff", "Mystic Staff", 0],
  [59, "energy_booster", "Energy Booster", 0],
  [60, "point_booster", "Point Booster", 0],
  [61, "vitality_booster", "Vitality Booster", 0],
  [63, "power_treads", "Power Treads", 0],
  [65, "hand_of_midas", "Hand of Midas", 0],
  [67, "oblivion_staff", "Oblivion Staff", 0],
  [69, "pers", "Perseverance", 0],
  [71, "poor_mans_shield", "Poor Man's Shield", 1],
  [73, "bracer", "Bracer", 0],
  [75, "wraith_band", "Wraith Band", 0],
  [77, "null_talisman", "Null Talisman", 0],
  [79, "mekansm", "Mekansm", 0],
  [81, "vladmir", "Vladmir's Offering", 0],
  [86, "buckler", "Buckler", 0],
  [88, "ring_of_basilius", "Ring of Basilius", 0],
  [90, "pipe", "Pipe of Insight", 0],
  [92, "urn_of_shadows", "Urn of Shadows", 0],
  [94, "headdress", "Headdress", 0],
  [96, "sheepstick", "Scythe of Vyse", 0],
  [98, "orchid", "Orchid Malevolence", 0],
  [100, "cyclone", "Eul's Scepter of Divinity", 0],
  [102, "force_staff", "Force Staff", 0],
  [104, "dagon", "Dagon", 0],
  [106, "necronomicon", "Necronomicon", 0],
  [108, "ultimate_scepter", "Aghanim's Scepter", 0],
  [110, "refresher", "Refresher Orb", 0],
  [112, "assault", "Assault Cuirass", 0],
  [114, "heart", "Heart of Tarrasque", 0],
  [116, "black_king_bar", "Black King Bar", 0],
  [117, "aegis", "Aegis of the Immortal", 0],
  [119, "shivas_guard", "Shiva's Guard", 0],
  [121, "bloodstone", "Bloodstone", 0],
  [123, "sphere", "Linken's Sphere", 0],
  [125, "vanguard", "Vanguard", 0],
  [127, "blade_mail", "Blade Mail", 0],
  [129, "soul_booster", "Soul Booster", 0],
  [131, "hood_of_defiance", "Hood of Defiance", 0],
  [133, "rapier", "Divine Rapier", 0],
  [135, "monkey_king_bar", "Monkey King Bar", 0],
  [137, "radiance", "Radiance", 0],
  [139, "butterfly", "Butterfly", 0],
  [141, "greater_crit", "Daedalus", 0],
  [143, "basher", "Skull Basher", 0],
  [145, "bfury", "Battle Fury", 0],
  [147, "manta", "Manta Style", 0],
  [149, "lesser_crit", "Crystalys", 0],
  [151, "armlet", "Armlet of Mordiggian", 0],
  [152, "invis_sword", "Shadow Blade", 0],
  [154, "sange_and_yasha", "Sange and Yasha", 0],
  [156, "satanic", "Satanic", 0],
  [158, "mjollnir", "Mjollnir", 0],
  [160, "skadi", "Eye of Skadi", 0],
  [162, "sange", "Sange", 0],
  [164, "helm_of_the_dominator", "Helm of the Dominator", 0],
  [166, "maelstrom", "Maelstrom", 0],
  [168, "desolator", "Desolator", 0],
  [170, "yasha", "Yasha", 0],
  [172, "mask_of_madness", "Mask of Madness", 0],
  [174, "diffusal_blade", "Diffusal Blade", 0],
  [176, "ethereal_blade", "Ethereal Blade", 0],
  [178, "soul_ring", "Soul Ring", 0],
  [180, "arcane_boots", "Arcane Boots", 0],
  [181, "orb_of_venom", "Orb of Venom", 0],
  [182, "stout_shield", "Stout Shield", 0],
  [185, "ancient_janggo", "Drum of Endurance", 0],
  [187, "medallion_of_courage", "Medallion of Courage", 1],
  [188, "smoke_of_deceit", "Smoke of Deceit", 0],
  [190, "veil_of_discord", "Veil of Discord", 0],
  [193, "necronomicon_2", "Necronomicon", 0],
  [194, "necronomicon_3", "Necronomicon", 0],
  [196, "diffusal_blade_2", "Diffusal Blade", 0],
  [201, "dagon_2", "Dagon", 0],
  [202, "dagon_3", "Dagon", 0],
  [203, "dagon_4", "Dagon", 0],
  [204, "dagon_5", "Dagon", 0],
  [206, "rod_of_atos", "Rod of Atos", 0],
  [208, "abyssal_blade", "Abyssal Blade", 0],
  [210, "heavens_halberd", "Heaven's Halberd", 0],
  [212, "ring_of_aquila", "Ring of Aquila", 0],
  [214, "tranquil_boots", "Tranquil Boots", 0],
  [215, "shadow_amulet", "Shadow Amulet", 0],
  [216, "enchanted_mango", "Enchanted Mango", 0],
  [218, "ward_dispenser", "Observer and Sentry Wards", 0],
  [220, "travel_boots_2", "Boots of Travel 2", 0],
  [223, "meteor_hammer", "Meteor Hammer", 0],
  [225, "nullifier", "Nullifier", 0],
  [226, "lotus_orb", "Lotus Orb", 0],
  [229, "solar_crest", "Solar Crest", 0],
  [231, "guardian_greaves", "Guardian Greaves", 0],
  [232, "aether_lens", "Aether Lens", 0],
  [235, "octarine_core", "Octarine Core", 0],
  [236, "dragon_lance", "Dragon Lance", 0],
  [237, "faerie_fire", "Faerie Fire", 0],
  [239, "iron_talon", "Iron Talon", 0],
  [240, "blight_stone", "Orb of Blight", 0],
  [241, "tango_single", "Tango (Shared)", 0],
  [242, "crimson_guard", "Crimson Guard", 0],
  [244, "wind_lace", "Wind Lace", 0],
  [247, "moon_shard", "Moon Shard", 0],
  [249, "silver_edge", "Silver Edge", 0],
  [250, "bloodthorn", "Bloodthorn", 0],
  [252, "echo_sabre", "Echo Sabre", 0],
  [254, "glimmer_cape", "Glimmer Cape", 0],
  [256, "aeon_disk", "Aeon Disk", 0],
  [257, "tome_of_knowledge", "Tome of Knowledge", 0],
  [259, "kaya", "Kaya", 0],
  [260, "refresher_shard", "Refresher Shard", 0],
  [261, "crown", "Crown", 0],
  [263, "hurricane_pike", "Hurricane Pike", 0],
  [265, "infused_raindrop", "Infused Raindrops", 0],
  [267, "spirit_vessel", "Spirit Vessel", 0],
  [269, "holy_locket", "Holy Locket", 0],
  [271, "ultimate_scepter_2", "Aghanim's Blessing", 0],
  [273, "kaya_and_sange", "Kaya and Sange", 0],
  [277, "yasha_and_kaya", "Yasha and Kaya", 0],
  [279, "ring_of_tarrasque", "Ring of Tarrasque", 0],
  [286, "flying_courier", "Flying Courier", 0],
  [287, "keen_optic", "Keen Optic", 0],
  [288, "grove_bow", "Grove Bow", 0],
  [289, "quickening_charm", "Quickening Charm", 0],
  [290, "philosophers_stone", "Philosopher's Stone", 0],
  [291, "force_boots", "Force Boots", 0],
  [292, "desolator_2", "Stygian Desolator", 1],
  [293, "phoenix_ash", "Phoenix Ash", 0],
  [294, "seer_stone", "Seer Stone", 0],
  [295, "greater_mango", "Greater Mango", 0],
  [297, "vampire_fangs", "Vampire Fangs", 0],
  [298, "craggy_coat", "Craggy Coat", 0],
  [299, "greater_faerie_fire", "Greater Faerie Fire", 0],
  [300, "timeless_relic", "Timeless Relic", 0],
  [301, "mirror_shield", "Mirror Shield", 0],
  [302, "elixer", "Elixir", 0],
  [304, "ironwood_tree", "Ironwood Tree", 0],
  [305, "royal_jelly", "Royal Jelly", 0],
  [306, "pupils_gift", "Pupil's Gift", 0],
  [307, "tome_of_aghanim", "Tome of Aghanim", 0],
  [308, "repair_kit", "Repair Kit", 0],
  [309, "mind_breaker", "Mind Breaker", 0],
  [310, "third_eye", "Third Eye", 0],
  [311, "spell_prism", "Spell Prism", 0],
  [312, "horizon", "Horizon", 0],
  [313, "fusion_rune", "Fusion Rune", 0],
  [325, "princes_knife", "Prince's Knife", 0],
  [326, "spider_legs", "Spider Legs", 1],
  [327, "helm_of_the_undying", "Helm of the Undying", 0],
  [328, "mango_tree", "Mango Tree", 0],
  [330, "witless_shako", "Witless Shako", 0],
  [331, "vambrace", "Vambrace", 0],
  [334, "imp_claw", "Imp Claw", 0],
  [335, "flicker", "Flicker", 0],
  [336, "spy_gadget", "Telescope", 0],
  [349, "arcane_ring", "Arcane Ring", 0],
  [354, "ocean_heart", "Ocean Heart", 0],
  [355, "broom_handle", "Broom Handle", 0],
  [356, "trusty_shovel", "Trusty Shovel", 0],
  [357, "nether_shawl", "Nether Shawl", 0],
  [358, "dragon_scale", "Dragon Scale", 0],
  [359, "essence_ring", "Essence Ring", 1],
  [360, "clumsy_net", "Clumsy Net", 0],
  [361, "enchanted_quiver", "Enchanted Quiver", 0],
  [362, "ninja_gear", "Ninja Gear", 0],
  [363, "illusionsts_cape", "Illusionist's Cape", 0],
  [364, "havoc_hammer", "Havoc Hammer", 0],
  [365, "panic_button", "Magic Lamp", 0],
  [366, "apex", "Apex", 0],
  [367, "ballista", "Ballista", 0],
  [368, "woodland_striders", "Woodland Striders", 0],
  [369, "trident", "Trident", 0],
  [370, "demonicon", "Book of the Dead", 1],
  [371, "fallen_sky", "Fallen Sky", 1],
  [372, "pirate_hat", "Pirate Hat", 0],
  [374, "ex_machina", "Ex Machina", 0],
  [375, "faded_broach", "Faded Broach", 0],
  [376, "paladin_sword", "Paladin Sword", 0],
  [377, "minotaur_horn", "Minotaur Horn", 1],
  [378, "orb_of_destruction", "Orb of Destruction", 0],
  [379, "the_leveller", "The Leveller", 0],
  [381, "titan_sliver", "Titan Sliver", 0],
  [473, "voodoo_mask", "Voodoo Mask", 0],
  [485, "blitz_knuckles", "Blitz Knuckles", 0],
  [534, "witch_blade", "Witch Blade", 0],
  [565, "chipped_vest", "Chipped Vest", 1],
  [569, "orb_of_corrosion", "Orb of Corrosion", 0],
  [571, "trickster_cloak", "Trickster Cloak", 0],
  [573, "elven_tunic", "Elven Tunic", 0],
  [574, "cloak_of_flames", "Cloak of Flames", 1],
  [577, "possessed_mask", "Possessed Mask", 1],
  [585, "stormcrafter", "Stormcrafter", 1],
  [589, "mysterious_hat", "Fairy's Trinket", 0],
  [593, "fluffy_hat", "Fluffy Hat", 0],
  [596, "falcon_blade", "Falcon Blade", 0],
  [598, "mage_slayer", "Mage Slayer", 0],
  [600, "overwhelming_blink", "Overwhelming Blink", 0],
  [603, "swift_blink", "Swift Blink", 0],
  [604, "arcane_blink", "Arcane Blink", 0],
  [609, "aghanims_shard", "Aghanim's Shard", 0],
  [610, "wind_waker", "Wind Waker", 0],
  [635, "helm_of_the_overlord", "Helm of the Overlord", 0],
  [638, "penta_edged_sword", "Penta-Edged Sword", 0],
  [675, "psychic_headband", "Psychic Headband", 1],
  [676, "ceremonial_robe", "Ceremonial Robe", 0],
  [677, "book_of_shadows", "Book of Shadows", 0],
  [678, "giants_ring", "Giant's Ring", 0],
  [680, "bullwhip", "Bullwhip", 0],
  [686, "quicksilver_amulet", "Quicksilver Amulet", 0],
  [692, "eternal_shroud", "Eternal Shroud", 0],
  [725, "aghanims_shard_roshan", "Aghanim's Shard - Consumable", 0],
  [727, "ultimate_scepter_roshan", "Aghanim's Blessing - Roshan", 0],
  [825, "ascetic_cap", "Ascetic's Cap", 0],
  [828, "misericorde", "Brigand's Blade", 0],
  [829, "force_field", "Arcanist's Armor", 0],
  [834, "black_powder_bag", "Blast Rig", 0],
  [835, "paintball", "Fae Grenade", 0],
  [837, "heavy_blade", "Witchbane", 1],
  [838, "unstable_wand", "Pig Pole", 0],
  [840, "pogo_stick", "Tumbler's Toy", 1],
  [849, "mechanical_arm", "Mechanical Arm", 0],
  [908, "wraith_pact", "Wraith Pact", 0],
  [911, "revenants_brooch", "Revenant's Brooch", 0],
  [931, "boots_of_bearing", "Boots of Bearing", 0],
  [939, "harpoon", "Harpoon", 0],
  [945, "seeds_of_serenity", "Seeds of Serenity", 1],
  [946, "lance_of_pursuit", "Lance of Pursuit", 0],
  [947, "occult_bracelet", "Occult Bracelet", 1],
  [949, "ogre_seal_totem", "Ogre Seal Totem", 0],
  [950, "defiant_shell", "Defiant Shell", 1],
  [990, "eye_of_the_vizier", "Eye of the Vizier", 0],
  [1000, "bottomless_chalice", "Bottomless Chalice", 0],
  [1021, "river_painter", "River Vial: Chrome", 0],
  [1022, "river_painter2", "River Vial: Dry", 0],
  [1023, "river_painter3", "River Vial: Slime", 0],
  [1024, "river_painter4", "River Vial: Oil", 0],
  [1025, "river_painter5", "River Vial: Electrified", 0],
  [1026, "river_painter6", "River Vial: Potion", 0],
  [1027, "river_painter7", "River Vial: Blood", 0],
  [1028, "mutation_tombstone", "Tombstone", 0],
  [1029, "super_blink", "Super Blink", 0],
  [1030, "pocket_tower", "Pocket Tower", 0],
  [1032, "pocket_roshan", "Pocket Roshan", 0],
  [1076, "specialists_array", "Specialist's Array", 0],
  [1077, "dagger_of_ristul", "Dagger of Ristul", 1],
  [1090, "muertas_gun", "Mercy & Grace", 0],
  [1097, "disperser", "Disperser", 0],
  [1107, "phylactery", "Phylactery", 0],
  [1122, "diadem", "Diadem", 0],
  [1123, "blood_grenade", "Blood Grenade", 0],
  [1124, "spark_of_courage", "Spark of Courage", 0],
  [1125, "cornucopia", "Cornucopia", 0],
  [1128, "pavise", "Pavise", 0],
  [1154, "royale_with_cheese", "Block of Cheese", 0],
  [1156, "ancient_guardian", "Ancient Guardian", 0],
  [1157, "safety_bubble", "Safety Bubble", 0],
  [1158, "whisper_of_the_dread", "Whisper of the Dread", 0],
  [1159, "nemesis_curse", "Nemesis Curse", 0],
  [1160, "avianas_feather", "Aviana's Feather", 0],
  [1161, "unwavering_condition", "Unwavering Condition", 0],
  [1167, "light_collector", "Light Collector", 0],
  [1168, "rattlecage", "Rattlecage", 1],
  [1440, "black_grimoire", "Black Grimoire\\n(Warlock)", 0],
  [1441, "grisgris", "Gris-Gris", 0],
  [1466, "gungir", "Gleipnir", 0],
  [1575, "orb_of_frost", "Orb of Frost", 0],
  [1576, "enhancement_vast", "Vast", 0],
  [1577, "enhancement_quickened", "Quickened", 0],
  [1581, "enhancement_audacious", "Audacious", 0],
  [1583, "enhancement_mystical", "Mystical", 0],
  [1584, "enhancement_alert", "Alert", 0],
  [1585, "enhancement_brawny", "Brawny", 0],
  [1586, "enhancement_tough", "Tough", 0],
  [1587, "enhancement_feverish", "Feverish", 0],
  [1588, "enhancement_fleetfooted", "Fleetfooted", 0],
  [1589, "enhancement_crude", "Crude", 0],
  [1590, "enhancement_boundless", "Boundless", 0],
  [1591, "enhancement_wise", "Wise", 0],
  [1592, "enhancement_timeless", "Timeless", 0],
  [1593, "enhancement_greedy", "Greedy", 0],
  [1594, "enhancement_vampiric", "Vampiric", 0],
  [1595, "enhancement_keen_eyed", "Keen-eyed", 0],
  [1596, "enhancement_evolved", "Evolved", 0],
  [1597, "enhancement_titanic", "Titanic", 0],
  [1598, "unrelenting_eye", "Unrelenting Eye", 1],
  [1599, "mana_draught", "Mana Draught", 1],
  [1600, "rippers_lash", "Ripper's Lash", 0],
  [1601, "crippling_crossbow", "Crippling Crossbow", 1],
  [1602, "gale_guard", "Gale Guard", 0],
  [1603, "gunpowder_gauntlets", "Gunpowder Gauntlet", 1],
  [1604, "searing_signet", "Searing Signet", 1],
  [1605, "serrated_shiv", "Serrated Shiv", 1],
  [1606, "polliwog_charm", "Pollywog Charm", 1],
  [1607, "magnifying_monocle", "Magnifying Monocle", 0],
  [1608, "pyrrhic_cloak", "Pyrrhic Cloak", 0],
  [1609, "madstone_bundle", "Madstone Bundle", 0],
  [1610, "miniboss_minion_summoner", "Miniboss Minion Summoner", 0],
  [1637, "kobold_cup", "Kobold Cup", 1],
  [1638, "dormant_curio", "Dormant Curio", 1],
  [1639, "sisters_shroud", "Sister's Shroud", 0],
  [1640, "jidi_pollen_bag", "Jidi Pollen Bag", 1],
  [1641, "outworld_staff", "Outworld Staff", 0],
  [1642, "dezun_bloodrite", "Dezun Bloodrite", 1],
  [1643, "giant_maul", "Giant's Maul", 1],
  [1644, "divine_regalia", "Divine Regalia", 1],
  [1645, "divine_regalia_broken", "Disgraced Regalia", 0],
  [1647, "enhancement_fierce", "Fierce", 0],
  [1648, "enhancement_dominant", "Dominant", 0],
  [1649, "enhancement_restorative", "Restorative", 0],
  [1650, "enhancement_thick", "Thick", 0],
  [1651, "enhancement_curious", "Unleashed", 0],
  [1652, "furion_gold_bag", "Bag of Gold", 0],
  [1716, "weighted_dice", "Weighted Dice", 1],
  [1717, "ash_legion_shield", "Ash Legion Shield", 1],
  [1718, "riftshadow_prism", "Riftshadow Prism", 1],
  [1719, "metamorphic_mandible", "Metamorphic Mandible", 1],
  [1720, "idol_of_screeauk", "Idol of Scree'auk", 1],
  [1721, "flayers_bota", "Flayer's Bota", 1],
  [1801, "caster_rapier", "Caster Rapier", 0],
  [1802, "tiara_of_selemene", "Tiara of Selemene", 0],
  [1803, "doubloon", "Doubloon", 0],
  [1804, "roshans_banner", "Roshan's Banner", 0],
  [1806, "devastator", "Parasma", 0],
  [1808, "angels_demise", "Khanda", 0],
  [1847, "splintmail", "Splintmail", 0],
  [1848, "shawl", "Shawl", 0],
  [1849, "wizard_hat", "Wizard Hat", 0],
  [1850, "eldwurms_edda", "Eldwurm's Edda", 0],
  [1852, "essence_distiller", "Essence Distiller", 0],
  [1854, "consecrated_wraps", "Consecrated Wraps", 0],
  [1856, "crellas_crozier", "Crella's Crozier", 0],
  [1858, "hydras_breath", "Hydra's Breath", 0],
  [1859, "spellslinger", "Spellslinger", 1],
  [1860, "prophets_pendulum", "Prophet's Pendulum", 1],
  [1861, "stonefeather_satchel", "Stonefeather Satchel", 1],
  [1862, "enchanters_bauble", "Enchanter's Bauble", 1],
  [1863, "harmonizer", "Harmonizer", 1],
  [1864, "conjurers_catalyst", "Conjurer's Catalyst", 1],
  [1865, "enhancement_vital", "Vital", 0],
  [1866, "enhancement_hulking", "Hulking", 0],
  [1867, "enhancement_manic", "Manic", 0],
  [1868, "foragers_kit", "Forager's Kit", 1],
  [1869, "foragers_health", "Vital Toadstool", 0],
  [1870, "foragers_stats", "Ironwood Nut", 0],
  [1871, "foragers_mana", "Tomo'kan Ringcap", 0],
  [1872, "chasm_stone", "Chasm Stone", 0],
  [1873, "partisans_brand", "Partisan's Brand", 1],
  [1874, "enhancement_nimble", "Nimble", 0],
  [1875, "tidehunter_fish", "Leviathan's Fish", 0],
  [2091, "tier1_token", "Tier 1 Token", 0],
  [2092, "tier2_token", "Tier 2 Token", 0],
  [2093, "tier3_token", "Tier 3 Token", 0],
  [2094, "tier4_token", "Tier 4 Token", 0],
  [2095, "tier5_token", "Tier 5 Token", 0],
  [2096, "vindicators_axe", "Vindicator's Axe", 0],
  [2097, "duelist_gloves", "Duelist Gloves", 1],
  [2190, "dandelion_amulet", "Dandelion Amulet", 1],
  [2192, "martyrs_plate", "Martyr's Plate", 0],
  [2193, "gossamer_cape", "Gossamer Cape", 0],
  [4204, "famango", "Healing Lotus", 0],
  [4205, "great_famango", "Great Healing Lotus", 0],
  [4206, "greater_famango", "Greater Healing Lotus", 0],
  [4300, "ofrenda", "Beloved Memory", 0],
  [4301, "ofrenda_shovel", "Scrying Shovel", 0],
  [4302, "ofrenda_pledge", "Forebearer's Fortune", 0],
];
